// Code generated by collections-gen. DO NOT EDIT.

package collections

import (
	"sort"
)

// Byte is a collection of byte values.
type Byte struct {
	items []byte
}

// NewByte creates a new collection from a slice of byte.
func NewByte(items []byte) *Byte {
	return &Byte{items}
}

// Interface returns the underlying slice used by the collection as interface{}
// value.
func (c *Byte) Interface() interface{} {
	return c.items
}

// Items returns the underlying slice of byte values used by the
// collection.
func (c *Byte) Items() []byte {
	return c.items
}

// EachIndex calls fn for every item in the collection. The slice index of the
// item is passed to fn as the second argument.
func (c *Byte) EachIndex(fn func(byte, int)) {
	for i, item := range c.items {
		fn(item, i)
	}
}

// Each calls fn for every item in the collection.
func (c *Byte) Each(fn func(byte)) {
	c.EachIndex(func(item byte, _ int) {
		fn(item)
	})
}

// IndexOf searches for el in the collection and returns the first index where
// el is found. If el is not present in the collection IndexOf will return -1.
func (c *Byte) IndexOf(el byte) int {
	for i, item := range c.items {
		if item == el {
			return i
		}
	}

	return -1
}

// First returns the first item from the collection. Will panic if the
// underlying slice is empty.
func (c *Byte) First() byte {
	return c.Nth(0)
}

// FirstN returns the first n byte items of the collection. Will
// return less than n items if the underlying slice's length is < n.
func (c *Byte) FirstN(n int) []byte {
	if n > c.Len() {
		return c.Items()
	}

	return c.Slice(0, n)
}

// Last returns the last item from the collection. Will panic if the underlying
// slice is empty.
func (c *Byte) Last() byte {
	return c.Nth(c.Len() - 1)
}

// LastN returns the last n byte items of the collection. Will return
// less than n items if the underlying slice's length is < n.
func (c *Byte) LastN(n int) []byte {
	if c.Len()-n < 0 {
		return c.Items()
	}

	return c.Slice(c.Len()-n, c.Len())
}

// Get returns the item at pos from the collection. Will panic if the
// underlying slice is shorter than pos+1.
func (c *Byte) Get(pos int) byte {
	return c.Nth(pos)
}

// Nth returns the nth item from the collection. Will panic if the underlying
// slice is shorter than pos+1.
func (c *Byte) Nth(pos int) byte {
	return c.items[pos]
}

// Len returns the length of the underlying byte slice.
func (c *Byte) Len() int {
	return len(c.items)
}

// Cap returns the capacity of the underlying byte slice.
func (c *Byte) Cap() int {
	return cap(c.items)
}

// Append appends items and returns the collection.
func (c *Byte) Append(items ...byte) *Byte {
	c.items = append(c.items, items...)
	return c
}

// Prepend prepends items and returns the collection.
func (c *Byte) Prepend(items ...byte) *Byte {
	c.items = append(items, c.items...)
	return c
}

// Copy creates a copy of the collection and the underlying byte slice.
func (c *Byte) Copy() *Byte {
	s := make([]byte, c.Len(), c.Len())
	copy(s, c.items)

	return NewByte(s)
}

// Filter removes all items from the collection for which fn evaluates to
// false and returns c.
func (c *Byte) Filter(fn func(byte) bool) *Byte {
	s := c.items[:0]

	for _, item := range c.items {
		if fn(item) {
			s = append(s, item)
		}
	}

	var zeroValue byte

	for i := len(s); i < len(c.items); i++ {
		c.items[i] = zeroValue
	}

	c.items = s

	return c
}

// Collect removes all items from the collection for which fn evaluates to
// false and returns c.
func (c *Byte) Collect(fn func(byte) bool) *Byte {
	return c.Filter(fn)
}

// Reject removes all items from the collection for which fn evaluates to
// true and returns c.
func (c *Byte) Reject(fn func(byte) bool) *Byte {
	return c.Filter(func(v byte) bool {
		return !fn(v)
	})
}

// Partition partitions the collection into two new collections. The first
// collection contains all items where fn evaluates to true, the second one all
// items where fn evaluates to false.
func (c *Byte) Partition(fn func(byte) bool) (*Byte, *Byte) {
	lhs := make([]byte, 0, c.Len())
	rhs := make([]byte, 0, c.Len())

	for _, item := range c.items {
		if fn(item) {
			lhs = append(lhs, item)
		} else {
			rhs = append(rhs, item)
		}
	}

	return NewByte(lhs), NewByte(rhs)
}

// Map calls fn for each item in the collection an replaces its value with the
// result of fn.
func (c *Byte) Map(fn func(byte) byte) *Byte {
	return c.MapIndex(func(item byte, _ int) byte {
		return fn(item)
	})
}

// MapIndex calls fn for each item in the collection an replaces its value with the
// result of fn.
func (c *Byte) MapIndex(fn func(byte, int) byte) *Byte {
	for i, item := range c.items {
		c.items[i] = fn(item, i)

	}

	return c
}

// Reduce calls fn for each item in c and reduces the result into reducer. The
// reducer contains the value returned by the call to fn for the previous item.
// Reducer will be the zero byte value on the first invocation.
func (c *Byte) Reduce(fn func(reducer byte, item byte) byte) byte {
	var reducer byte

	for _, item := range c.items {
		reducer = fn(reducer, item)
	}

	return reducer
}

// Find returns the first item for which fn evaluates to true. If the
// collection does not contain a matching item, Find will return the zero
// byte value. If you need to distinguish zero values from a condition
// that did not match any item consider using FindOk instead.
func (c *Byte) Find(fn func(byte) bool) byte {
	item, _ := c.FindOk(fn)

	return item
}

// FindOk returns the first item for which fn evaluates to true. If the
// collection does not contain a matching item, FindOk will return the zero
// byte value. The second return value denotes whether the condition
// matched any item or not.
func (c *Byte) FindOk(fn func(byte) bool) (byte, bool) {
	for _, item := range c.items {
		if fn(item) {
			return item, true
		}
	}

	var zeroValue byte
	return zeroValue, false
}

// Any returns true as soon as fn evaluates to true for one item in c.
func (c *Byte) Any(fn func(byte) bool) bool {
	for _, item := range c.items {
		if fn(item) {
			return true
		}
	}

	return false
}

// All returns true if fn evaluates to true for all items in c.
func (c *Byte) All(fn func(byte) bool) bool {
	for _, item := range c.items {
		if !fn(item) {
			return false
		}
	}

	return true
}

// Contains returns true if the collection contains el.
func (c *Byte) Contains(el byte) bool {
	for _, item := range c.items {
		if item == el {
			return true
		}
	}

	return false
}

// Sort sorts the collection using the passed in comparator func.
func (c *Byte) Sort(fn func(byte, byte) bool) *Byte {
	sort.Slice(c.items, c.lessFunc(fn))
	return c
}

// IsSorted returns true if the collection is sorted in the order defined by
// the passed in comparator func.
func (c *Byte) IsSorted(fn func(byte, byte) bool) bool {
	return sort.SliceIsSorted(c.items, c.lessFunc(fn))
}

func (c *Byte) lessFunc(fn func(byte, byte) bool) func(int, int) bool {
	return func(i, j int) bool {
		return fn(c.items[i], c.items[j])
	}
}

// Reverse reverses the order of the collection items in place and returns c.
func (c *Byte) Reverse() *Byte {
	for l, r := 0, len(c.items)-1; l < r; l, r = l+1, r-1 {
		c.items[l], c.items[r] = c.items[r], c.items[l]
	}

	return c
}

// Remove removes the collection item at position pos. Will panic if pos is out
// of bounds.
func (c *Byte) Remove(pos int) *Byte {
	c.items = append(c.items[:pos], c.items[pos+1:]...)
	return c
}

// RemoveItem removes all instances of item from the collection and returns it.
func (c *Byte) RemoveItem(item byte) *Byte {
	for i, el := range c.items {
		if el == item {
			c.items = append(c.items[:i], c.items[i+1:]...)
		}
	}

	return c
}

// InsertItem inserts item into the collection at position pos. Will panic if
// pos is out of bounds.
func (c *Byte) InsertItem(item byte, pos int) *Byte {
	var zeroValue byte
	c.items = append(c.items, zeroValue)
	copy(c.items[pos+1:], c.items[pos:])
	c.items[pos] = item
	return c
}

// Cut returns a copy of the underlying byte slice with the items
// between index i and j removed. Will panic if i or j is out of bounds of the
// underlying slice.
func (c *Byte) Cut(i, j int) []byte {
	s := make([]byte, 0, c.Len())
	s = append(s, c.items[:i]...)
	return append(s, c.items[j:]...)
}

// Slice returns the byte items between slice index i and j. Will
// panic if i or j is out of bounds.
func (c *Byte) Slice(i, j int) []byte {
	return c.items[i:j]
}
