// +build !ignore_autogenerated

// Code generated by collection-gen. DO NOT EDIT.

package collections

import (
	"sort"
)

// ImmutableInt is an immutable collection of int values.
type ImmutableInt struct {
	items []int
}

// NewImmutableInt creates a new immutable collection from a slice of int.
func NewImmutableInt(items []int) *ImmutableInt {
	return &ImmutableInt{items}
}

// Interface returns the underlying slice used by the collection as interface{}
// value.
func (c *ImmutableInt) Interface() interface{} {
	return c.items
}

// Items returns the underlying slice of int values used by the
// collection.
func (c *ImmutableInt) Items() []int {
	return c.items
}

// EachIndex calls fn for every item in the collection. The slice index of the
// item is passed to fn as the second argument.
func (c *ImmutableInt) EachIndex(fn func(int, int)) {
	for i, item := range c.items {
		fn(item, i)
	}
}

// Each calls fn for every item in the collection.
func (c *ImmutableInt) Each(fn func(int)) {
	c.EachIndex(func(item int, _ int) {
		fn(item)
	})
}

// IndexOf searches for el in the collection and returns the first index where
// el is found. If el is not present in the collection IndexOf will return -1.
func (c *ImmutableInt) IndexOf(el int) int {
	for i, item := range c.items {
		if item == el {
			return i
		}
	}

	return -1
}

// First returns the first item from the collection. Will panic if the
// underlying slice is empty.
func (c *ImmutableInt) First() int {
	return c.Nth(0)
}

// FirstN returns the first n int items of the collection. Will
// return less than n items if the underlying slice's length is < n.
func (c *ImmutableInt) FirstN(n int) []int {
	if n > c.Len() {
		return c.Copy().Items()
	}

	return c.Slice(0, n)
}

// Last returns the last item from the collection. Will panic if the underlying
// slice is empty.
func (c *ImmutableInt) Last() int {
	return c.Nth(c.Len() - 1)
}

// LastN returns the last n int items of the collection. Will return
// less than n items if the underlying slice's length is < n.
func (c *ImmutableInt) LastN(n int) []int {
	if c.Len()-n < 0 {
		return c.Copy().Items()
	}

	return c.Slice(c.Len()-n, c.Len())
}

// Get returns the item at pos from the collection. Will panic if the
// underlying slice is shorter than pos+1.
func (c *ImmutableInt) Get(pos int) int {
	return c.Nth(pos)
}

// Nth returns the nth item from the collection. Will panic if the underlying
// slice is shorter than pos+1.
func (c *ImmutableInt) Nth(pos int) int {
	return c.items[pos]
}

// Len returns the length of the underlying int slice.
func (c *ImmutableInt) Len() int {
	return len(c.items)
}

// Cap returns the capacity of the underlying int slice.
func (c *ImmutableInt) Cap() int {
	return cap(c.items)
}

// Append appends items and returns the collection. The
// original collection will not be modified.
func (c *ImmutableInt) Append(items ...int) *ImmutableInt {
	d := c.Copy()
	d.items = append(d.items, items...)
	return d
}

// Prepend prepends items and returns the collection. The
// original collection will not be modified.
func (c *ImmutableInt) Prepend(items ...int) *ImmutableInt {
	d := c.Copy()
	d.items = append(items, d.items...)
	return d
}

// Copy creates a copy of the collection and the underlying int slice.
func (c *ImmutableInt) Copy() *ImmutableInt {
	s := make([]int, c.Len(), c.Len())
	copy(s, c.items)

	return NewImmutableInt(s)
}

// Filter collects all items for which fn evaluates to true into a new
// collection. The original collection is not altered.
func (c *ImmutableInt) Filter(fn func(int) bool) *ImmutableInt {
	d := c.Copy()
	s := d.items[:0]

	for _, item := range d.items {
		if fn(item) {
			s = append(s, item)
		}
	}

	var zeroValue int

	for i := len(s); i < len(d.items); i++ {
		d.items[i] = zeroValue
	}

	d.items = s

	return d
}

// Collect collects all items for which fn evaluates to true into a new
// collection. The original collection is not altered.
func (c *ImmutableInt) Collect(fn func(int) bool) *ImmutableInt {
	return c.Filter(fn)
}

// Reject collects all items for which fn evaluates to false into a new
// collection. The original collection is not altered.
func (c *ImmutableInt) Reject(fn func(int) bool) *ImmutableInt {
	return c.Filter(func(v int) bool {
		return !fn(v)
	})
}

// Partition partitions the collection into two new collections. The first
// collection contains all items where fn evaluates to true, the second one all
// items where fn evaluates to false.
func (c *ImmutableInt) Partition(fn func(int) bool) (*ImmutableInt, *ImmutableInt) {
	lhs := make([]int, 0, c.Len())
	rhs := make([]int, 0, c.Len())

	for _, item := range c.items {
		if fn(item) {
			lhs = append(lhs, item)
		} else {
			rhs = append(rhs, item)
		}
	}

	return NewImmutableInt(lhs), NewImmutableInt(rhs)
}

// Map calls fn for each item in the collection an replaces its value with the
// result of fn. The result is a new collection. The original
// collection is not modified.
func (c *ImmutableInt) Map(fn func(int) int) *ImmutableInt {
	return c.MapIndex(func(item int, _ int) int {
		return fn(item)
	})
}

// MapIndex calls fn for each item in the collection an replaces its value with the
// result of fn. The result is a new collection. The original
// collection is not modified.
func (c *ImmutableInt) MapIndex(fn func(int, int) int) *ImmutableInt {
	d := c.Copy()

	for i, item := range d.items {
		d.items[i] = fn(item, i)

	}

	return d
}

// Reduce calls fn for each item in c and reduces the result into reducer. The
// reducer contains the value returned by the call to fn for the previous item.
// Reducer will be the zero int value on the first invocation.
func (c *ImmutableInt) Reduce(fn func(reducer int, item int) int) int {
	var reducer int

	for _, item := range c.items {
		reducer = fn(reducer, item)
	}

	return reducer
}

// Find returns the first item for which fn evaluates to true. If the
// collection does not contain a matching item, Find will return the zero
// int value. If you need to distinguish zero values from a condition
// that did not match any item consider using FindOk instead.
func (c *ImmutableInt) Find(fn func(int) bool) int {
	item, _ := c.FindOk(fn)

	return item
}

// FindOk returns the first item for which fn evaluates to true. If the
// collection does not contain a matching item, FindOk will return the zero
// int value. The second return value denotes whether the condition
// matched any item or not.
func (c *ImmutableInt) FindOk(fn func(int) bool) (int, bool) {
	for _, item := range c.items {
		if fn(item) {
			return item, true
		}
	}

	var zeroValue int
	return zeroValue, false
}

// Any returns true as soon as fn evaluates to true for one item in c.
func (c *ImmutableInt) Any(fn func(int) bool) bool {
	for _, item := range c.items {
		if fn(item) {
			return true
		}
	}

	return false
}

// All returns true if fn evaluates to true for all items in c.
func (c *ImmutableInt) All(fn func(int) bool) bool {
	for _, item := range c.items {
		if !fn(item) {
			return false
		}
	}

	return true
}

// Contains returns true if the collection contains el.
func (c *ImmutableInt) Contains(el int) bool {
	for _, item := range c.items {
		if item == el {
			return true
		}
	}

	return false
}

// Sort sorts the collection using the passed in comparator func.
// The result will be a copy of c which is sorted, the original collection is
// not altered.
func (c *ImmutableInt) Sort(fn func(int, int) bool) *ImmutableInt {
	d := c.Copy()
	sort.Slice(d.items, d.lessFunc(fn))
	return d
}

// IsSorted returns true if the collection is sorted in the order defined by
// the passed in comparator func.
func (c *ImmutableInt) IsSorted(fn func(int, int) bool) bool {
	return sort.SliceIsSorted(c.items, c.lessFunc(fn))
}

func (c *ImmutableInt) lessFunc(fn func(int, int) bool) func(int, int) bool {
	return func(i, j int) bool {
		return fn(c.items[i], c.items[j])
	}
}

// Reverse copies the collection and returns it with the order of all items
// reversed.
func (c *ImmutableInt) Reverse() *ImmutableInt {
	d := c.Copy()
	for l, r := 0, len(d.items)-1; l < r; l, r = l+1, r-1 {
		d.items[l], d.items[r] = d.items[r], d.items[l]
	}

	return d
}

// Remove removes the collection item at position pos. Will panic if pos is out
// of bounds.
// The result is a new collection, the original is not modified.
func (c *ImmutableInt) Remove(pos int) *ImmutableInt {
	d := c.Copy()
	d.items = append(d.items[:pos], d.items[pos+1:]...)
	return d
}

// RemoveItem removes all instances of item from the collection and returns it.
// The result is a new collection, the original is not modified.
func (c *ImmutableInt) RemoveItem(item int) *ImmutableInt {
	d := c.Copy()

	for i, el := range d.items {
		if el == item {
			d.items = append(d.items[:i], d.items[i+1:]...)
		}
	}

	return d
}

// InsertItem inserts item into the collection at position pos. Will panic if
// pos is out of bounds.
// The result is a new collection, the original is not modified.
func (c *ImmutableInt) InsertItem(item int, pos int) *ImmutableInt {
	var zeroValue int
	d := c.Copy()
	d.items = append(d.items, zeroValue)
	copy(d.items[pos+1:], d.items[pos:])
	d.items[pos] = item
	return d
}

// Cut returns a copy of the underlying int slice with the items
// between index i and j removed. Will panic if i or j is out of bounds of the
// underlying slice.
func (c *ImmutableInt) Cut(i, j int) []int {
	d := c.Copy()
	return append(d.items[:i], d.items[j:]...)
}

// Slice returns the int items between slice index i and j. Will
// panic if i or j is out of bounds.
func (c *ImmutableInt) Slice(i, j int) []int {
	return c.Copy().items[i:j]
}
