// Code generated by collections-gen. DO NOT EDIT.

package collections

import (
	"sort"
)

// ImmutableString is an immutable collection of string values.
type ImmutableString struct {
	items []string
}

// NewImmutableString creates a new immutable collection from a slice of string.
func NewImmutableString(items []string) *ImmutableString {
	return &ImmutableString{items}
}

// Interface returns the underlying slice used by the collection as interface{}
// value.
func (c *ImmutableString) Interface() interface{} {
	return c.items
}

// Items returns the underlying slice of string values used by the
// collection.
func (c *ImmutableString) Items() []string {
	return c.items
}

// EachIndex calls fn for every item in the collection. The slice index of the
// item is passed to fn as the second argument.
func (c *ImmutableString) EachIndex(fn func(string, int)) {
	for i, item := range c.items {
		fn(item, i)
	}
}

// Each calls fn for every item in the collection.
func (c *ImmutableString) Each(fn func(string)) {
	c.EachIndex(func(item string, _ int) {
		fn(item)
	})
}

// IndexOf searches for el in the collection and returns the first index where
// el is found. If el is not present in the collection IndexOf will return -1.
func (c *ImmutableString) IndexOf(el string) int {
	for i, item := range c.items {
		if item == el {
			return i
		}
	}

	return -1
}

// First returns the first item from the collection. Will panic if the
// underlying slice is empty.
func (c *ImmutableString) First() string {
	return c.Nth(0)
}

// FirstN returns the first n string items of the collection. Will
// return less than n items if the underlying slice's length is < n.
func (c *ImmutableString) FirstN(n int) []string {
	if n > c.Len() {
		return c.Copy().Items()
	}

	return c.Slice(0, n)
}

// Last returns the last item from the collection. Will panic if the underlying
// slice is empty.
func (c *ImmutableString) Last() string {
	return c.Nth(c.Len() - 1)
}

// LastN returns the last n string items of the collection. Will return
// less than n items if the underlying slice's length is < n.
func (c *ImmutableString) LastN(n int) []string {
	if c.Len()-n < 0 {
		return c.Copy().Items()
	}

	return c.Slice(c.Len()-n, c.Len())
}

// Get returns the item at pos from the collection. Will panic if the
// underlying slice is shorter than pos+1.
func (c *ImmutableString) Get(pos int) string {
	return c.Nth(pos)
}

// Nth returns the nth item from the collection. Will panic if the underlying
// slice is shorter than pos+1.
func (c *ImmutableString) Nth(pos int) string {
	return c.items[pos]
}

// Len returns the length of the underlying string slice.
func (c *ImmutableString) Len() int {
	return len(c.items)
}

// Cap returns the capacity of the underlying string slice.
func (c *ImmutableString) Cap() int {
	return cap(c.items)
}

// Append appends items and returns the collection. The
// original collection will not be modified.
func (c *ImmutableString) Append(items ...string) *ImmutableString {
	d := c.Copy()
	d.items = append(d.items, items...)
	return d
}

// Prepend prepends items and returns the collection. The
// original collection will not be modified.
func (c *ImmutableString) Prepend(items ...string) *ImmutableString {
	d := c.Copy()
	d.items = append(items, d.items...)
	return d
}

// Copy creates a copy of the collection and the underlying string slice.
func (c *ImmutableString) Copy() *ImmutableString {
	s := make([]string, c.Len(), c.Len())
	copy(s, c.items)

	return NewImmutableString(s)
}

// Filter collects all items for which fn evaluates to true into a new
// collection. The original collection is not altered.
func (c *ImmutableString) Filter(fn func(string) bool) *ImmutableString {
	d := c.Copy()
	s := d.items[:0]

	for _, item := range d.items {
		if fn(item) {
			s = append(s, item)
		}
	}

	var zeroValue string

	for i := len(s); i < len(d.items); i++ {
		d.items[i] = zeroValue
	}

	d.items = s

	return d
}

// Collect collects all items for which fn evaluates to true into a new
// collection. The original collection is not altered.
func (c *ImmutableString) Collect(fn func(string) bool) *ImmutableString {
	return c.Filter(fn)
}

// Reject collects all items for which fn evaluates to false into a new
// collection. The original collection is not altered.
func (c *ImmutableString) Reject(fn func(string) bool) *ImmutableString {
	return c.Filter(func(v string) bool {
		return !fn(v)
	})
}

// Partition partitions the collection into two new collections. The first
// collection contains all items where fn evaluates to true, the second one all
// items where fn evaluates to false.
func (c *ImmutableString) Partition(fn func(string) bool) (*ImmutableString, *ImmutableString) {
	lhs := make([]string, 0, c.Len())
	rhs := make([]string, 0, c.Len())

	for _, item := range c.items {
		if fn(item) {
			lhs = append(lhs, item)
		} else {
			rhs = append(rhs, item)
		}
	}

	return NewImmutableString(lhs), NewImmutableString(rhs)
}

// Map calls fn for each item in the collection an replaces its value with the
// result of fn. The result is a new collection. The original
// collection is not modified.
func (c *ImmutableString) Map(fn func(string) string) *ImmutableString {
	d := c.Copy()

	for i, item := range d.items {
		d.items[i] = fn(item)

	}

	return d
}

// Reduce calls fn for each item in c and reduces the result into reducer. The
// reducer contains the value returned by the call to fn for the previous item.
// Reducer will be the zero string value on the first invocation.
func (c *ImmutableString) Reduce(fn func(reducer string, item string) string) string {
	var reducer string

	for _, item := range c.items {
		reducer = fn(reducer, item)
	}

	return reducer
}

// Find returns the first item for which fn evaluates to true. If the
// collection does not contain a matching item, Find will return the zero
// string value. If you need to distinguish zero values from a condition
// that did not match any item consider using FindOk instead.
func (c *ImmutableString) Find(fn func(string) bool) string {
	item, _ := c.FindOk(fn)

	return item
}

// FindOk returns the first item for which fn evaluates to true. If the
// collection does not contain a matching item, FindOk will return the zero
// string value. The second return value denotes whether the condition
// matched any item or not.
func (c *ImmutableString) FindOk(fn func(string) bool) (string, bool) {
	for _, item := range c.items {
		if fn(item) {
			return item, true
		}
	}

	var zeroValue string
	return zeroValue, false
}

// Any returns true as soon as fn evaluates to true for one item in c.
func (c *ImmutableString) Any(fn func(string) bool) bool {
	for _, item := range c.items {
		if fn(item) {
			return true
		}
	}

	return false
}

// All returns true if fn evaluates to true for all items in c.
func (c *ImmutableString) All(fn func(string) bool) bool {
	for _, item := range c.items {
		if !fn(item) {
			return false
		}
	}

	return true
}

// Contains returns true if the collection contains el.
func (c *ImmutableString) Contains(el string) bool {
	for _, item := range c.items {
		if item == el {
			return true
		}
	}

	return false
}

// Sort sorts the collection using the passed in comparator func.
// The result will be a copy of c which is sorted, the original collection is
// not altered.
func (c *ImmutableString) Sort(fn func(string, string) bool) *ImmutableString {
	d := c.Copy()
	sort.Slice(d.items, d.lessFunc(fn))
	return d
}

// IsSorted returns true if the collection is sorted in the order defined by
// the passed in comparator func.
func (c *ImmutableString) IsSorted(fn func(string, string) bool) bool {
	return sort.SliceIsSorted(c.items, c.lessFunc(fn))
}

func (c *ImmutableString) lessFunc(fn func(string, string) bool) func(int, int) bool {
	return func(i, j int) bool {
		return fn(c.items[i], c.items[j])
	}
}

// Reverse copies the collection and returns it with the order of all items
// reversed.
func (c *ImmutableString) Reverse() *ImmutableString {
	d := c.Copy()
	for l, r := 0, len(d.items)-1; l < r; l, r = l+1, r-1 {
		d.items[l], d.items[r] = d.items[r], d.items[l]
	}

	return d
}

// Remove removes the collection item at position pos. Will panic if pos is out
// of bounds.
// The result is a new collection, the original is not modified.
func (c *ImmutableString) Remove(pos int) *ImmutableString {
	d := c.Copy()
	d.items = append(d.items[:pos], d.items[pos+1:]...)
	return d
}

// RemoveItem removes all instances of item from the collection and returns it.
// The result is a new collection, the original is not modified.
func (c *ImmutableString) RemoveItem(item string) *ImmutableString {
	d := c.Copy()

	for i, el := range d.items {
		if el == item {
			d.items = append(d.items[:i], d.items[i+1:]...)
		}
	}

	return d
}

// InsertItem inserts item into the collection at position pos. Will panic if
// pos is out of bounds.
// The result is a new collection, the original is not modified.
func (c *ImmutableString) InsertItem(item string, pos int) *ImmutableString {
	var zeroValue string
	d := c.Copy()
	d.items = append(d.items, zeroValue)
	copy(d.items[pos+1:], d.items[pos:])
	d.items[pos] = item
	return d
}

// Cut returns a copy of the underlying string slice with the items
// between index i and j removed. Will panic if i or j is out of bounds of the
// underlying slice.
func (c *ImmutableString) Cut(i, j int) []string {
	d := c.Copy()
	return append(d.items[:i], d.items[j:]...)
}

// Slice returns the string items between slice index i and j. Will
// panic if i or j is out of bounds.
func (c *ImmutableString) Slice(i, j int) []string {
	return c.Copy().items[i:j]
}
