// Code generated by collections-gen. DO NOT EDIT.

package collections

import (
	"sort"
)

// StringCollection is a collection of string values.
type StringCollection struct {
	items []string
}

// NewStringCollection creates a new collection from a slice of string.
func NewStringCollection(items []string) *StringCollection {
	return &StringCollection{items}
}

// Items returns the underlying slice of string values used by the
// collection.
func (c *StringCollection) Items() []string {
	return c.items
}

func (c *StringCollection) EachIndex(fn func(string, int)) {
	for i, item := range c.items {
		fn(item, i)
	}
}

func (c *StringCollection) Each(fn func(string)) {
	c.EachIndex(func(item string, _ int) {
		fn(item)
	})
}

func (c *StringCollection) IndexOf(el string) int {
	for i, item := range c.items {
		if item == el {
			return i
		}
	}

	return -1
}

func (c *StringCollection) First() string {
	return c.Nth(0)
}

func (c *StringCollection) FirstN(n int) *StringCollection {
	if n > c.Len() {
		n = c.Len()
	}

	return c.Slice(0, n)
}

func (c *StringCollection) Last() string {
	return c.Nth(c.Len() - 1)
}

func (c *StringCollection) LastN(n int) *StringCollection {
	if c.Len()-n < 0 {
		n = c.Len()
	}

	return c.Slice(c.Len()-n, c.Len())
}

func (c *StringCollection) Get(idx int) string {
	return c.Nth(idx)
}

func (c *StringCollection) Nth(idx int) string {
	return c.items[idx]
}

func (c *StringCollection) Len() int {
	return len(c.items)
}

func (c *StringCollection) Cap() int {
	return cap(c.items)
}

func (c *StringCollection) Append(items ...string) *StringCollection {
	c.items = append(c.items, items...)

	return c
}

func (c *StringCollection) Prepend(items ...string) *StringCollection {
	c.items = append(items, c.items...)

	return c
}

func (c *StringCollection) Copy() *StringCollection {
	s := make([]string, c.Len(), c.Len())
	copy(s, c.items)

	return NewStringCollection(s)
}

func (c *StringCollection) Filter(fn func(string) bool) *StringCollection {
	s := c.items[:0]

	for _, item := range c.items {
		if fn(item) {
			s = append(s, item)
		}
	}

	for i := len(s); i < len(c.items); i++ {
		c.items[i] = ""
	}

	c.items = s

	return c
}

func (c *StringCollection) Collect(fn func(string) bool) *StringCollection {
	return c.Filter(fn)
}

func (c *StringCollection) Reject(fn func(string) bool) *StringCollection {
	return c.Filter(func(v string) bool {
		return !fn(v)
	})
}

func (c *StringCollection) Partition(fn func(string) bool) (*StringCollection, *StringCollection) {
	lhs := make([]string, 0, c.Len())
	rhs := make([]string, 0, c.Len())

	for _, item := range c.items {
		if fn(item) {
			lhs = append(lhs, item)
		} else {
			rhs = append(rhs, item)
		}
	}

	return NewStringCollection(lhs), NewStringCollection(rhs)
}

func (c *StringCollection) Map(fn func(string) string) *StringCollection {
	for i, item := range c.items {
		c.items[i] = fn(item)

	}

	return c
}

func (c *StringCollection) Reduce(fn func(reducer string, item string) string) string {
	var reducer string

	for _, item := range c.items {
		reducer = fn(reducer, item)
	}

	return reducer
}

func (c *StringCollection) Find(fn func(string) bool) string {
	item, _ := c.FindOk(fn)

	return item
}

func (c *StringCollection) FindOk(fn func(string) bool) (string, bool) {
	for _, item := range c.items {
		if fn(item) {
			return item, true
		}
	}

	return "", false
}

func (c *StringCollection) Any(fn func(string) bool) bool {
	for _, item := range c.items {
		if fn(item) {
			return true
		}
	}

	return false
}

func (c *StringCollection) All(fn func(string) bool) bool {
	for _, item := range c.items {
		if !fn(item) {
			return false
		}
	}

	return true
}

func (c *StringCollection) Contains(el string) bool {
	for _, item := range c.items {
		if item == el {
			return true
		}
	}

	return false
}

func (c *StringCollection) Sort(fn func(string, string) bool) *StringCollection {
	sort.Slice(c.items, c.lessFunc(fn))

	return c
}

func (c *StringCollection) IsSorted(fn func(string, string) bool) bool {
	return sort.SliceIsSorted(c.items, c.lessFunc(fn))
}

func (c *StringCollection) lessFunc(fn func(string, string) bool) func(int, int) bool {
	return func(i, j int) bool {
		return fn(c.items[i], c.items[j])
	}
}

func (c *StringCollection) Reverse() *StringCollection {
	for l, r := 0, len(c.items)-1; l < r; l, r = l+1, r-1 {
		c.items[l], c.items[r] = c.items[r], c.items[l]
	}

	return c
}

func (c *StringCollection) Remove(idx int) *StringCollection {
	c.items = append(c.items[:idx], c.items[idx+1:]...)

	return c
}

func (c *StringCollection) RemoveItem(item string) *StringCollection {
	for i, el := range c.items {
		if el == item {
			c.items = append(c.items[:i], c.items[i+1:]...)
		}
	}

	return c
}

func (c *StringCollection) InsertItem(item string, idx int) *StringCollection {
	c.items = append(c.items, "")
	copy(c.items[idx+1:], c.items[idx:])
	c.items[idx] = item

	return c
}

func (c *StringCollection) Cut(i, j int) *StringCollection {
	c.items = append(c.items[:i], c.items[j:]...)

	return c
}

func (c *StringCollection) Slice(i, j int) *StringCollection {
	c.items = c.items[i:j]

	return c
}
