// Code generated by collections-gen. DO NOT EDIT.

package immutable

import (
	"sort"
)

// BoolCollection is an immutable collection of bool values.
type BoolCollection struct {
	items []bool
}

// NewBoolCollection creates a new immutable collection from a slice of bool.
func NewBoolCollection(items []bool) *BoolCollection {
	return &BoolCollection{items}
}

// Items returns the underlying slice of bool values used by the
// collection.
func (c *BoolCollection) Items() []bool {
	return c.items
}

func (c *BoolCollection) EachIndex(fn func(bool, int)) {
	for i, item := range c.items {
		fn(item, i)
	}
}

func (c *BoolCollection) Each(fn func(bool)) {
	c.EachIndex(func(item bool, _ int) {
		fn(item)
	})
}

func (c *BoolCollection) IndexOf(el bool) int {
	for i, item := range c.items {
		if item == el {
			return i
		}
	}

	return -1
}

func (c *BoolCollection) First() bool {
	return c.Nth(0)
}

func (c *BoolCollection) FirstN(n int) *BoolCollection {
	if n > c.Len() {
		n = c.Len()
	}

	return c.Slice(0, n)
}

func (c *BoolCollection) Last() bool {
	return c.Nth(c.Len() - 1)
}

func (c *BoolCollection) LastN(n int) *BoolCollection {
	if c.Len()-n < 0 {
		n = c.Len()
	}

	return c.Slice(c.Len()-n, c.Len())
}

func (c *BoolCollection) Get(idx int) bool {
	return c.Nth(idx)
}

func (c *BoolCollection) Nth(idx int) bool {
	return c.items[idx]
}

func (c *BoolCollection) Len() int {
	return len(c.items)
}

func (c *BoolCollection) Cap() int {
	return cap(c.items)
}

func (c *BoolCollection) Append(items ...bool) *BoolCollection {
	d := c.Copy()
	d.items = append(d.items, items...)

	return d
}

func (c *BoolCollection) Prepend(items ...bool) *BoolCollection {
	d := c.Copy()
	d.items = append(items, d.items...)

	return d
}

func (c *BoolCollection) Copy() *BoolCollection {
	s := make([]bool, c.Len(), c.Len())
	copy(s, c.items)

	return NewBoolCollection(s)
}

func (c *BoolCollection) Filter(fn func(bool) bool) *BoolCollection {
	d := c.Copy()
	s := d.items[:0]

	for _, item := range d.items {
		if fn(item) {
			s = append(s, item)
		}
	}

	for i := len(s); i < len(d.items); i++ {
		d.items[i] = false
	}

	d.items = s

	return d
}

func (c *BoolCollection) Collect(fn func(bool) bool) *BoolCollection {
	return c.Filter(fn)
}

func (c *BoolCollection) Reject(fn func(bool) bool) *BoolCollection {
	return c.Filter(func(v bool) bool {
		return !fn(v)
	})
}

func (c *BoolCollection) Partition(fn func(bool) bool) (*BoolCollection, *BoolCollection) {
	lhs := make([]bool, 0, c.Len())
	rhs := make([]bool, 0, c.Len())

	for _, item := range c.items {
		if fn(item) {
			lhs = append(lhs, item)
		} else {
			rhs = append(rhs, item)
		}
	}

	return NewBoolCollection(lhs), NewBoolCollection(rhs)
}

func (c *BoolCollection) Map(fn func(bool) bool) *BoolCollection {
	d := c.Copy()

	for i, item := range d.items {
		d.items[i] = fn(item)

	}

	return d
}

func (c *BoolCollection) Reduce(fn func(reducer bool, item bool) bool) bool {
	var reducer bool

	for _, item := range c.items {
		reducer = fn(reducer, item)
	}

	return reducer
}

func (c *BoolCollection) Find(fn func(bool) bool) bool {
	item, _ := c.FindOk(fn)

	return item
}

func (c *BoolCollection) FindOk(fn func(bool) bool) (bool, bool) {
	for _, item := range c.items {
		if fn(item) {
			return item, true
		}
	}

	return false, false
}

func (c *BoolCollection) Any(fn func(bool) bool) bool {
	for _, item := range c.items {
		if fn(item) {
			return true
		}
	}

	return false
}

func (c *BoolCollection) All(fn func(bool) bool) bool {
	for _, item := range c.items {
		if !fn(item) {
			return false
		}
	}

	return true
}

func (c *BoolCollection) Contains(el bool) bool {
	for _, item := range c.items {
		if item == el {
			return true
		}
	}

	return false
}

func (c *BoolCollection) Sort(fn func(bool, bool) bool) *BoolCollection {
	d := c.Copy()
	sort.Slice(d.items, d.lessFunc(fn))

	return d
}

func (c *BoolCollection) IsSorted(fn func(bool, bool) bool) bool {
	return sort.SliceIsSorted(c.items, c.lessFunc(fn))
}

func (c *BoolCollection) lessFunc(fn func(bool, bool) bool) func(int, int) bool {
	return func(i, j int) bool {
		return fn(c.items[i], c.items[j])
	}
}

func (c *BoolCollection) Reverse() *BoolCollection {
	d := c.Copy()
	for l, r := 0, len(d.items)-1; l < r; l, r = l+1, r-1 {
		d.items[l], d.items[r] = d.items[r], d.items[l]
	}

	return d
}

func (c *BoolCollection) Remove(idx int) *BoolCollection {
	d := c.Copy()
	d.items = append(d.items[:idx], d.items[idx+1:]...)

	return d
}

func (c *BoolCollection) RemoveItem(item bool) *BoolCollection {
	d := c.Copy()

	for i, el := range c.items {
		if el == item {
			d.items = append(d.items[:i], d.items[i+1:]...)
		}
	}

	return d
}

func (c *BoolCollection) InsertItem(item bool, idx int) *BoolCollection {
	d := c.Copy()
	d.items = append(d.items, false)
	copy(d.items[idx+1:], d.items[idx:])
	d.items[idx] = item

	return d
}

func (c *BoolCollection) Cut(i, j int) *BoolCollection {
	d := c.Copy()
	d.items = append(d.items[:i], d.items[j:]...)

	return d
}

func (c *BoolCollection) Slice(i, j int) *BoolCollection {
	d := c.Copy()
	d.items = d.items[i:j]

	return d
}
