// Code generated by collections-gen. DO NOT EDIT.

package immutable

import (
	"sort"
)

// BoolCollection is an immutable collection of bool values.
type BoolCollection struct {
	items []bool
}

// NewBoolCollection creates a new immutable collection from a slice of bool.
func NewBoolCollection(items []bool) *BoolCollection {
	return &BoolCollection{items}
}

// Items returns the underlying slice of bool values used by the
// collection.
func (c *BoolCollection) Items() []bool {
	return c.items
}

// EachIndex calls fn for every item in the collection. The slice index of the
// item is passed to fn as the second argument.
func (c *BoolCollection) EachIndex(fn func(bool, int)) {
	for i, item := range c.items {
		fn(item, i)
	}
}

// Each calls fn for every item in the collection.
func (c *BoolCollection) Each(fn func(bool)) {
	c.EachIndex(func(item bool, _ int) {
		fn(item)
	})
}

// IndexOf searches for el in the collection and returns the first index where
// el is found. If el is not present in the collection IndexOf will return -1.
func (c *BoolCollection) IndexOf(el bool) int {
	for i, item := range c.items {
		if item == el {
			return i
		}
	}

	return -1
}

// First returns the first item from the collection. Will panic if the
// underlying slice is empty.
func (c *BoolCollection) First() bool {
	return c.Nth(0)
}

// FirstN returns a new collection containing the first n items. Will return
// less than n items if the underlying slice's length is < n.
func (c *BoolCollection) FirstN(n int) *BoolCollection {
	if n > c.Len() {
		n = c.Len()
	}

	return c.Slice(0, n)
}

// Last returns the last item from the collection. Will panic if the underlying
// slice is empty.
func (c *BoolCollection) Last() bool {
	return c.Nth(c.Len() - 1)
}

// LastN returns a new collection containing the last n items. Will return less
// than n items if the underlying slice's length is < n.
func (c *BoolCollection) LastN(n int) *BoolCollection {
	if c.Len()-n < 0 {
		n = c.Len()
	}

	return c.Slice(c.Len()-n, c.Len())
}

// Get returns the item at idx from the collection. Will panic if the
// underlying slice is shorter than idx+1.
func (c *BoolCollection) Get(idx int) bool {
	return c.Nth(idx)
}

// Nth returns the nth item from the collection. Will panic if the underlying
// slice is shorter than idx+1.
func (c *BoolCollection) Nth(idx int) bool {
	return c.items[idx]
}

// Len returns the length of the underlying bool slice.
func (c *BoolCollection) Len() int {
	return len(c.items)
}

// Cap returns the capacity of the underlying bool slice.
func (c *BoolCollection) Cap() int {
	return cap(c.items)
}

// Append appends items and returns the collection. The
// original collection will not be modified.
func (c *BoolCollection) Append(items ...bool) *BoolCollection {
	d := c.Copy()
	d.items = append(d.items, items...)
	return d
}

// Prepend prepends items and returns the collection. The
// original collection will not be modified.
func (c *BoolCollection) Prepend(items ...bool) *BoolCollection {
	d := c.Copy()
	d.items = append(items, d.items...)
	return d
}

// Copy creates a copy of the collection and the underlying bool slice.
func (c *BoolCollection) Copy() *BoolCollection {
	s := make([]bool, c.Len(), c.Len())
	copy(s, c.items)

	return NewBoolCollection(s)
}

// Filter collects all items for which fn evaluates to true into a new
// collection. The original collection is not altered.
func (c *BoolCollection) Filter(fn func(bool) bool) *BoolCollection {
	d := c.Copy()
	s := d.items[:0]

	for _, item := range d.items {
		if fn(item) {
			s = append(s, item)
		}
	}

	var zeroValue bool

	for i := len(s); i < len(d.items); i++ {
		d.items[i] = zeroValue
	}

	d.items = s

	return d
}

// Collect collects all items for which fn evaluates to true into a new
// collection. The original collection is not altered.
func (c *BoolCollection) Collect(fn func(bool) bool) *BoolCollection {
	return c.Filter(fn)
}

// Reject collects all items for which fn evaluates to false into a new
// collection. The original collection is not altered.
func (c *BoolCollection) Reject(fn func(bool) bool) *BoolCollection {
	return c.Filter(func(v bool) bool {
		return !fn(v)
	})
}

// Partition partitions the collection into two new collections. The first
// collection contains all items where fn evaluates to true, the second one all
// items where fn evaluates to false.
func (c *BoolCollection) Partition(fn func(bool) bool) (*BoolCollection, *BoolCollection) {
	lhs := make([]bool, 0, c.Len())
	rhs := make([]bool, 0, c.Len())

	for _, item := range c.items {
		if fn(item) {
			lhs = append(lhs, item)
		} else {
			rhs = append(rhs, item)
		}
	}

	return NewBoolCollection(lhs), NewBoolCollection(rhs)
}

// Map calls fn for each item in the collection an replaces its value with the
// result of fn. The result is a new collection. The original
// collection is not modified.
func (c *BoolCollection) Map(fn func(bool) bool) *BoolCollection {
	d := c.Copy()

	for i, item := range d.items {
		d.items[i] = fn(item)

	}

	return d
}

// Reduce calls fn for each item in c and reduces the result into reducer. The
// reducer contains the value returned by the call to fn for the previous item.
// Reducer will be the zero bool value on the first invocation.
func (c *BoolCollection) Reduce(fn func(reducer bool, item bool) bool) bool {
	var reducer bool

	for _, item := range c.items {
		reducer = fn(reducer, item)
	}

	return reducer
}

// Find returns the first item for which fn evaluates to true. If the
// collection does not contain a matching item, Find will return the zero
// bool value. If you need to distinguish zero values from a condition
// that did not match any item consider using FindOk instead.
func (c *BoolCollection) Find(fn func(bool) bool) bool {
	item, _ := c.FindOk(fn)

	return item
}

// FindOk returns the first item for which fn evaluates to true. If the
// collection does not contain a matching item, FindOk will return the zero
// bool value. The second return value denotes whether the condition
// matched any item or not.
func (c *BoolCollection) FindOk(fn func(bool) bool) (bool, bool) {
	for _, item := range c.items {
		if fn(item) {
			return item, true
		}
	}

	var zeroValue bool
	return zeroValue, false
}

// Any returns true as soon as fn evaluates to true for one item in c.
func (c *BoolCollection) Any(fn func(bool) bool) bool {
	for _, item := range c.items {
		if fn(item) {
			return true
		}
	}

	return false
}

// All returns true if fn evaluates to true for all items in c.
func (c *BoolCollection) All(fn func(bool) bool) bool {
	for _, item := range c.items {
		if !fn(item) {
			return false
		}
	}

	return true
}

// Contains returns true if the collection contains el.
func (c *BoolCollection) Contains(el bool) bool {
	for _, item := range c.items {
		if item == el {
			return true
		}
	}

	return false
}

// Sort sorts the collection using the passed in comparator func.
// The result will be a copy of c which is sorted, the original collection is
// not altered.
func (c *BoolCollection) Sort(fn func(bool, bool) bool) *BoolCollection {
	d := c.Copy()
	sort.Slice(d.items, d.lessFunc(fn))
	return d
}

// IsSorted returns true if the collection is sorted in the order defined by
// the passed in comparator func.
func (c *BoolCollection) IsSorted(fn func(bool, bool) bool) bool {
	return sort.SliceIsSorted(c.items, c.lessFunc(fn))
}

func (c *BoolCollection) lessFunc(fn func(bool, bool) bool) func(int, int) bool {
	return func(i, j int) bool {
		return fn(c.items[i], c.items[j])
	}
}

// Reverse copies the collection and returns it with the order of all items
// reversed.
func (c *BoolCollection) Reverse() *BoolCollection {
	d := c.Copy()
	for l, r := 0, len(d.items)-1; l < r; l, r = l+1, r-1 {
		d.items[l], d.items[r] = d.items[r], d.items[l]
	}

	return d
}

// Remove removes the collection item at position idx. Will panic if idx is out
// of bounds.
// The result is a new collection, the original is not modified.
func (c *BoolCollection) Remove(idx int) *BoolCollection {
	d := c.Copy()
	d.items = append(d.items[:idx], d.items[idx+1:]...)
	return d
}

// RemoveItem removes all instances of item from the collection and returns it.
// The result is a new collection, the original is not modified.
func (c *BoolCollection) RemoveItem(item bool) *BoolCollection {
	d := c.Copy()

	for i, el := range d.items {
		if el == item {
			d.items = append(d.items[:i], d.items[i+1:]...)
		}
	}

	return d
}

// InsertItem inserts item into the collection at position idx. Will panic if
// idx is out of bounds.
// The result is a new collection, the original is not modified.
func (c *BoolCollection) InsertItem(item bool, idx int) *BoolCollection {
	var zeroValue bool
	d := c.Copy()
	d.items = append(d.items, zeroValue)
	copy(d.items[idx+1:], d.items[idx:])
	d.items[idx] = item
	return d
}

// Cut removes all items between index i and j from the collection and returns
// it. Will panic if i or j is out of bounds of the underlying slice.
// The result is a new collection, the original is not modified.
func (c *BoolCollection) Cut(i, j int) *BoolCollection {
	d := c.Copy()
	d.items = append(d.items[:i], d.items[j:]...)
	return d
}

// Slice replaces the underlying slice of c with the items between i and j and
// returns the collection. Will panic if i or j is out of bounds.
// The result is a new collection, the original is not modified.
func (c *BoolCollection) Slice(i, j int) *BoolCollection {
	d := c.Copy()
	d.items = d.items[i:j]
	return d
}
