// Code generated by collections-gen. DO NOT EDIT.

package immutable

import (
	"sort"
)

// StringCollection is an immutable collection of string values.
type StringCollection struct {
	items []string
}

// NewStringCollection creates a new immutable collection from a slice of string.
func NewStringCollection(items []string) *StringCollection {
	return &StringCollection{items}
}

// Items returns the underlying slice of string values used by the
// collection.
func (c *StringCollection) Items() []string {
	return c.items
}

// EachIndex calls fn for every item in the collection. The slice index of the
// item is passed to fn as the second argument.
func (c *StringCollection) EachIndex(fn func(string, int)) {
	for i, item := range c.items {
		fn(item, i)
	}
}

// Each calls fn for every item in the collection.
func (c *StringCollection) Each(fn func(string)) {
	c.EachIndex(func(item string, _ int) {
		fn(item)
	})
}

// IndexOf searches for el in the collection and returns the first index where
// el is found. If el is not present in the collection IndexOf will return -1.
func (c *StringCollection) IndexOf(el string) int {
	for i, item := range c.items {
		if item == el {
			return i
		}
	}

	return -1
}

// First returns the first item from the collection. Will panic if the
// underlying slice is empty.
func (c *StringCollection) First() string {
	return c.Nth(0)
}

// FirstN returns a new collection containing the first n items. Will return
// less than n items if the underlying slice's length is < n.
func (c *StringCollection) FirstN(n int) *StringCollection {
	if n > c.Len() {
		n = c.Len()
	}

	return c.Slice(0, n)
}

// Last returns the last item from the collection. Will panic if the underlying
// slice is empty.
func (c *StringCollection) Last() string {
	return c.Nth(c.Len() - 1)
}

// LastN returns a new collection containing the last n items. Will return less
// than n items if the underlying slice's length is < n.
func (c *StringCollection) LastN(n int) *StringCollection {
	if c.Len()-n < 0 {
		n = c.Len()
	}

	return c.Slice(c.Len()-n, c.Len())
}

// Get returns the item at idx from the collection. Will panic if the
// underlying slice is shorter than idx+1.
func (c *StringCollection) Get(idx int) string {
	return c.Nth(idx)
}

// Nth returns the nth item from the collection. Will panic if the underlying
// slice is shorter than idx+1.
func (c *StringCollection) Nth(idx int) string {
	return c.items[idx]
}

// Len returns the length of the underlying string slice.
func (c *StringCollection) Len() int {
	return len(c.items)
}

// Cap returns the capacity of the underlying string slice.
func (c *StringCollection) Cap() int {
	return cap(c.items)
}

// Append appends items and returns the collection. The
// initial collection will not be modified.
func (c *StringCollection) Append(items ...string) *StringCollection {
	d := c.Copy()
	d.items = append(d.items, items...)
	return d
}

// Prepend prepends items and returns the collection. The
// initial collection will not be modified.
func (c *StringCollection) Prepend(items ...string) *StringCollection {
	d := c.Copy()
	d.items = append(items, d.items...)
	return d
}

// Copy creates a copy of the collection and the underlying string slice.
func (c *StringCollection) Copy() *StringCollection {
	s := make([]string, c.Len(), c.Len())
	copy(s, c.items)

	return NewStringCollection(s)
}

// Filter collects all items for which fn evaluates to true into a new
// collection. The inital collection is not altered.
func (c *StringCollection) Filter(fn func(string) bool) *StringCollection {
	d := c.Copy()
	s := d.items[:0]

	for _, item := range d.items {
		if fn(item) {
			s = append(s, item)
		}
	}

	for i := len(s); i < len(d.items); i++ {
		d.items[i] = ""
	}

	d.items = s

	return d
}

// Collect collects all items for which fn evaluates to true into a new
// collection. The inital collection is not altered.
func (c *StringCollection) Collect(fn func(string) bool) *StringCollection {
	return c.Filter(fn)
}

// Reject collects all items for which fn evaluates to false into a new
// collection. The inital collection is not altered.
func (c *StringCollection) Reject(fn func(string) bool) *StringCollection {
	return c.Filter(func(v string) bool {
		return !fn(v)
	})
}

// Partition partitions the collection into two new collections. The first
// collection contains all items where fn evaluates to true, the second one all
// items where fn evaluates to false.
func (c *StringCollection) Partition(fn func(string) bool) (*StringCollection, *StringCollection) {
	lhs := make([]string, 0, c.Len())
	rhs := make([]string, 0, c.Len())

	for _, item := range c.items {
		if fn(item) {
			lhs = append(lhs, item)
		} else {
			rhs = append(rhs, item)
		}
	}

	return NewStringCollection(lhs), NewStringCollection(rhs)
}

// Map calls fn for each item in the collection an replaces its value with the
// result of fn. The result is a new collection. The initial
// collection is not modified.
func (c *StringCollection) Map(fn func(string) string) *StringCollection {
	d := c.Copy()

	for i, item := range d.items {
		d.items[i] = fn(item)

	}

	return d
}

func (c *StringCollection) Reduce(fn func(reducer string, item string) string) string {
	var reducer string

	for _, item := range c.items {
		reducer = fn(reducer, item)
	}

	return reducer
}

func (c *StringCollection) Find(fn func(string) bool) string {
	item, _ := c.FindOk(fn)

	return item
}

func (c *StringCollection) FindOk(fn func(string) bool) (string, bool) {
	for _, item := range c.items {
		if fn(item) {
			return item, true
		}
	}

	return "", false
}

// Any returns true as soon as fn evaluates to true for one item in c.
func (c *StringCollection) Any(fn func(string) bool) bool {
	for _, item := range c.items {
		if fn(item) {
			return true
		}
	}

	return false
}

// All returns true if fn evaluates to true for all items in c.
func (c *StringCollection) All(fn func(string) bool) bool {
	for _, item := range c.items {
		if !fn(item) {
			return false
		}
	}

	return true
}

// Contains returns true if the collection contains el.
func (c *StringCollection) Contains(el string) bool {
	for _, item := range c.items {
		if item == el {
			return true
		}
	}

	return false
}

func (c *StringCollection) Sort(fn func(string, string) bool) *StringCollection {
	d := c.Copy()
	sort.Slice(d.items, d.lessFunc(fn))
	return d
}

func (c *StringCollection) IsSorted(fn func(string, string) bool) bool {
	return sort.SliceIsSorted(c.items, c.lessFunc(fn))
}

func (c *StringCollection) lessFunc(fn func(string, string) bool) func(int, int) bool {
	return func(i, j int) bool {
		return fn(c.items[i], c.items[j])
	}
}

func (c *StringCollection) Reverse() *StringCollection {
	d := c.Copy()
	for l, r := 0, len(d.items)-1; l < r; l, r = l+1, r-1 {
		d.items[l], d.items[r] = d.items[r], d.items[l]
	}

	return d
}

func (c *StringCollection) Remove(idx int) *StringCollection {
	d := c.Copy()
	d.items = append(d.items[:idx], d.items[idx+1:]...)
	return d
}

func (c *StringCollection) RemoveItem(item string) *StringCollection {
	d := c.Copy()

	for i, el := range c.items {
		if el == item {
			d.items = append(d.items[:i], d.items[i+1:]...)
		}
	}

	return d
}

func (c *StringCollection) InsertItem(item string, idx int) *StringCollection {
	d := c.Copy()
	d.items = append(d.items, "")
	copy(d.items[idx+1:], d.items[idx:])
	d.items[idx] = item
	return d
}

func (c *StringCollection) Cut(i, j int) *StringCollection {
	d := c.Copy()
	d.items = append(d.items[:i], d.items[j:]...)
	return d
}

func (c *StringCollection) Slice(i, j int) *StringCollection {
	d := c.Copy()
	d.items = d.items[i:j]
	return d
}
