package templates

var ImmutableCollection = `
// Code generated by collections-gen. DO NOT EDIT.

package {{.Package}}

import (
	"sort"
)

type {{.Name}} struct {
	items []{{.ItemType}}
}

func New{{.Name}}(items []{{.ItemType}}) *{{.Name}} {
	return &{{.Name}}{items}
}

func (c *{{.Name}}) Items() []{{.ItemType}} {
	return c.items
}

func (c *{{.Name}}) EachIndex(fn func({{.ItemType}}, int)) {
	for i, item := range c.items {
		fn(item, i)
	}
}

func (c *{{.Name}}) Each(fn func({{.ItemType}})) {
	c.EachIndex(func(item {{.ItemType}}, _ int) {
		fn(item)
	})
}

func (c *{{.Name}}) IndexOf(el {{.ItemType}}) int {
	for i, item := range c.items {
		if item == el {
			return i
		}
	}

	return -1
}

func (c *{{.Name}}) First() {{.ItemType}} {
	return c.Nth(0)
}

func (c *{{.Name}}) FirstN(n int) *{{.Name}} {
	if n > c.Len() {
		n = c.Len()
	}

	return c.Slice(0, n)
}

func (c *{{.Name}}) Last() {{.ItemType}} {
	return c.Nth(c.Len() - 1)
}

func (c *{{.Name}}) LastN(n int) *{{.Name}} {
	if c.Len()-n < 0 {
		n = c.Len()
	}

	return c.Slice(c.Len()-n, c.Len())
}

func (c *{{.Name}}) Get(idx int) {{.ItemType}} {
	return c.Nth(idx)
}

func (c *{{.Name}}) Nth(idx int) {{.ItemType}} {
	return c.items[idx]
}

func (c *{{.Name}}) Len() int {
	return len(c.items)
}

func (c *{{.Name}}) Cap() int {
	return cap(c.items)
}

func (c *{{.Name}}) Append(items ...{{.ItemType}}) *{{.Name}} {
	d := c.Copy()
	d.items = append(d.items, items...)

	return d
}

func (c *{{.Name}}) Prepend(items ...{{.ItemType}}) *{{.Name}} {
	d := c.Copy()
	d.items = append(items, d.items...)

	return d
}

func (c *{{.Name}}) Copy() *{{.Name}} {
	s := make([]{{.ItemType}}, c.Len(), c.Len())
	copy(s, c.items)

	return New{{.Name}}(s)
}

func (c *{{.Name}}) Filter(fn func({{.ItemType}}) bool) *{{.Name}} {
	d := c.Copy()
	s := d.items[:0]

	for _, item := range d.items {
		if fn(item) {
			s = append(s, item)
		}
	}

	for i := len(s); i < len(d.items); i++ {
		d.items[i] = {{.ZeroValue}}
	}

	d.items = s

	return d
}

func (c *{{.Name}}) Collect(fn func({{.ItemType}}) bool) *{{.Name}} {
	return c.Filter(fn)
}

func (c *{{.Name}}) Reject(fn func({{.ItemType}}) bool) *{{.Name}} {
	return c.Filter(func(v {{.ItemType}}) bool {
		return !fn(v)
	})
}

func (c *{{.Name}}) Partition(fn func({{.ItemType}}) bool) (*{{.Name}}, *{{.Name}}) {
	lhs := make([]{{.ItemType}}, 0, c.Len())
	rhs := make([]{{.ItemType}}, 0, c.Len())

	for _, item := range c.items {
		if fn(item) {
			lhs = append(lhs, item)
		} else {
			rhs = append(rhs, item)
		}
	}

	return New{{.Name}}(lhs), New{{.Name}}(rhs)
}

func (c *{{.Name}}) Map(fn func({{.ItemType}}) {{.ItemType}}) *{{.Name}} {
	d := c.Copy()

	for i, item := range d.items {
		d.items[i] = fn(item)

	}

	return d
}

func (c *{{.Name}}) Reduce(fn func(reducer {{.ItemType}}, item {{.ItemType}}) {{.ItemType}}) {{.ItemType}} {
	var reducer {{.ItemType}}

	for _, item := range c.items {
		reducer = fn(reducer, item)
	}

	return reducer
}

func (c *{{.Name}}) Find(fn func({{.ItemType}}) bool) {{.ItemType}} {
	item, _ := c.FindOk(fn)

	return item
}

func (c *{{.Name}}) FindOk(fn func({{.ItemType}}) bool) ({{.ItemType}}, bool) {
	for _, item := range c.items {
		if fn(item) {
			return item, true
		}
	}

	return {{.ZeroValue}}, false
}

func (c *{{.Name}}) Any(fn func({{.ItemType}}) bool) bool {
	for _, item := range c.items {
		if fn(item) {
			return true
		}
	}

	return false
}

func (c *{{.Name}}) All(fn func({{.ItemType}}) bool) bool {
	for _, item := range c.items {
		if !fn(item) {
			return false
		}
	}

	return true
}

func (c *{{.Name}}) Contains(el {{.ItemType}}) bool {
	for _, item := range c.items {
		if item == el {
			return true
		}
	}

	return false
}

func (c *{{.Name}}) Sort(fn func({{.ItemType}}, {{.ItemType}}) bool) *{{.Name}} {
	d := c.Copy()
	sort.Slice(d.items, d.lessFunc(fn))

	return d
}

func (c *{{.Name}}) IsSorted(fn func({{.ItemType}}, {{.ItemType}}) bool) bool {
	return sort.SliceIsSorted(c.items, c.lessFunc(fn))
}

func (c *{{.Name}}) lessFunc(fn func({{.ItemType}}, {{.ItemType}}) bool) func(int, int) bool {
	return func(i, j int) bool {
		return fn(c.items[i], c.items[j])
	}
}

func (c *{{.Name}}) Reverse() *{{.Name}} {
	d := c.Copy()
	for l, r := 0, len(d.items)-1; l < r; l, r = l+1, r-1 {
		d.items[l], d.items[r] = d.items[r], d.items[l]
	}

	return d
}

func (c *{{.Name}}) Remove(idx int) *{{.Name}} {
	d := c.Copy()
	d.items = append(d.items[:idx], d.items[idx+1:]...)

	return d
}

func (c *{{.Name}}) RemoveItem(item {{.ItemType}}) *{{.Name}} {
	d := c.Copy()

	for i, el := range c.items {
		if el == item {
			d.items = append(d.items[:i], d.items[i+1:]...)
		}
	}

	return d
}

func (c *{{.Name}}) InsertItem(item {{.ItemType}}, idx int) *{{.Name}} {
	d := c.Copy()
	d.items = append(d.items, {{.ZeroValue}})
	copy(d.items[idx+1:], d.items[idx:])
	d.items[idx] = item

	return d
}

func (c *{{.Name}}) Cut(i, j int) *{{.Name}} {
	d := c.Copy()
	d.items = append(d.items[:i], d.items[j:]...)

	return d
}

func (c *{{.Name}}) Slice(i, j int) *{{.Name}} {
	d := c.Copy()
	d.items = d.items[i:j]

	return d
}
`
